baseurl = "https://weekly.vincentxue.com/"
defaultContentLanguage = "zh"
locale = "zh"
title = "追光周刊"
theme = 'hugo-theme-dream-3.15.0'

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

author = "Vincent"
description = "追光周刊：每周分享我看到、分享以及创造的内容。"
avatar = "site-logo.png"
headerTitle = "追光周刊"
motto = "每周所见 · 所荐 · 所创"

# footerBottomText = ""

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2026

favicon = '<link rel="icon" href="/favicon.png" type="image/png" />'

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
showSummaryCoverInPost = true
# imageZoomableInPost = true
# showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
